# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f5f3b3955d448c9949b77612c9449e0e29dee9881ca9ecfc1b3f3dcb46b9a3bccaf724d87976a7d6c3e328cb7cd5ad98943ca7818b41b7fb1990386a7055138

test:
  secret_key_base: fc0de0a396cbcc5213fe959c7e0a628c69fd7ea8de014296abdeae61a81abc2407dd7917779952ec4f01eedc34ac12cca80c766f118f6ab37eff9bb70ebd94bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
